# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OC-Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'YYAsyncLayer'
  pod 'YYDispatchQueuePool'
  pod 'YYCache'
  pod 'YYImage'
  pod 'YYWebImage'
  

  # Pods for OC-Test

end
